"""Models for the Fumis WiRCU API."""


STATUS_OFF = "off"
STATUS_COLD_START_OFF = "cold start off"
STATUS_WOOD_BURNING_OFF = "wood burning off"
STATUS_PRE_HEATING = "pre_heating"
STATUS_IGNITION = "ignition"
STATUS_PRE_COMBUSTION = "pre_combustion"
STATUS_COMBUSTION = "combustion"
STATUS_ECO = "eco"
STATUS_COOLING = "cooling"
STATUS_UNKNOWN = "unknown"
STATUS_HYBRID_INIT = "hybrid init"
STATUS_HYBRID_START = "hybrid start"
STATUS_WOOD_START = "wood start"
STATUS_COLD_START = "cold start"
STATUS_WOODCOMBUSTION = "wood combustion"

STATUS_MAPPING = {
    0: STATUS_OFF,
    1: STATUS_COLD_START_OFF,
    2: STATUS_WOOD_BURNING_OFF,
    10: STATUS_PRE_HEATING,
    20: STATUS_IGNITION,
    21: STATUS_PRE_COMBUSTION,
    30: STATUS_COMBUSTION,
    40: STATUS_ECO,
    50: STATUS_COOLING,
    60: STATUS_HYBRID_INIT,
    80: STATUS_HYBRID_START,
    90: STATUS_WOOD_START,
    100: STATUS_COLD_START,
    110: STATUS_WOODCOMBUSTION,
}

STATE_OFF = "off"
STATE_ON = "on"
STATE_UNKNOWN = "unknown"

STATE_MAPPING = {
    1: STATE_OFF,
    2: STATE_ON,
}

ECO_MAPPING = {
    0: STATE_OFF,
    1: STATE_ON,
}
