"""Constants for the fumis integration."""
DOMAIN = "fumis"
ATTR_POWER = "kw"
ATTR_STATUS = "status"
ATTR_ACTUAL_POWER = "actualpower"
#ATTR_CONSUM_POWER = "kw"
ATTR_FUEL = "fuel_quantity"
ATTR_COMBUSTION_CHAMBER_TEMPERATURE = "combustion_chamber_temperature"
ATTR_TIME_TO_SERVICE = "time_to_service"
MANUFACTURER = "fumis"
TIMEOUT = 60
